eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@10.100.254.229:8761/eureka/,http://${security.user.name}:${security.user.password}@10.100.254.193:8761/eureka/

security:
  user:
    name: user
    password:  password

spring:
  application:
    name: mgr-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.100.254.11:5432/micro_cloud_auth
    username: myerp
    password: godblessme
  redis:
    host: 10.100.254.229
    password: bjc-2018
    port: 6379
    timeout: 0

system:
  proxy:
    user: system-service-sit

    
server:
  port: 7779

logging:
  level:
    root: info
  path: /tmp/log