spring:
  application:
    name: mgr-registry
  security:
    user:
      name: user
      password: password

# eureka的默认端口是8761
server:
  port: 8761

eureka:
  server:
    renewalPercentThreshold: 0.65
    #enableSelfPreservation: false                       #是否开启自我保护模式，默认为true。
    #eviction-interval-timer-in-ms: 15000         # eureka server清理无效节点的时间间隔（缺省为60*1000ms）
  instance:
     hostname: eureka-service
     prefer-ip-address: true                    #是否使用主机名来定义注册中心的地址  false：不使用
     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
     metadata-map:
       user.name: ${security.user.name}
       user.password: ${security.user.password}
  client:
    #registerWithEureka: false                #默认是true，将自己注册到eureka上
    #fetchRegistry: false                           #是否从eureka上获取信息，由于本案例是单机，无需从别的eureka上获取注册信息
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@10.100.254.229:8761/eureka/,http://${security.user.name}:${security.user.password}@10.100.254.193:8761/eureka/

logging:
  config: classpath:logback-spring.xml
  path: /tmp/log