eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

spring:
  application:
    name: mgr-getaway
  security:
    user:
      password: password
      name: user

server:
  port: 80

logging:
  path: applog
  level:
    org.springframework.security: debug
sys:
  login:
    model: bjc
    index: /system-web/index
  security:
    token-access:
      appName: mgr-auth
      clientId: bjc1
      secret: bjc-2018

